# specify directories
raw_reads_directory: data
output_directory: preprocessing
read_specification: ['1', '2'] # or ['R1', 'R2']
extension: .fastq.gz # or .fastq.gz (should be gzipped regardless) - must include the period!

# specify parameters for TrimGalore -- automatically chcecks the adaptor type
trim_galore:
  quality:  30
  min_read_length: 60
  start_trim: 0
  end_trim: 0

rm_host_reads:
  host_genome: /gpfs/data/schluterlab/bc3125/host_reference_genomes/hg19/hg19.fa
  # Mice: /labs/asbhatt/data/host_reference_genomes/mm10/mm10.fa
  # Humans: /gpfs/data/schluterlab/bc3125/host_reference_genomes/hg19/hg19.fa
